prompt_order = [
  "character",
  "username",
  "kubernetes",
  "directory",
  "git_branch",
  "git_status",
  "docker_context",
  "package",
  "nodejs",
  "elixir",
  "ruby",
  "rust",
  "python",
  "golang",
  "cmd_duration",
  "line_break",
  "jobs",
  "battery",
]

# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "âœ" symbol in the prompt with "â¯"
[character]      # The name of the module we are confguring is "character"
symbol = " Î»"     # The "symbol" segment is being set to "â¯"
error_symbol = " Î»"
use_symbol_for_status = true

[directory]
truncation_length = 5
truncate_to_repo = false


[git_status]
#conflicted = "ğŸ³"
#ahead = "ğŸğŸ’¨"
#behind = "ğŸ˜°"
#diverged = "ğŸ˜µ"
#untracked = "ğŸ¤·â€"
#stashed = "ğŸ“¦"
#modified = "ğŸ“"
#added = "â•"
#renamed = "ğŸ‘…"
#deleted = "ğŸ—‘"

[kubernetes]
disabled = false
symbol = ""

[line_break]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = false

